

@HOST=http://localhost:3000
@TOKEN=admin

### Prueba de calculadora
POST {{HOST}}/calculadora/Calcular HTTP/1.1

{
    "n1": 5,
    "n2":5,
    "operacion": "+"
}

### Prueba de calculadora
GET {{HOST}}/calculadora/Historial HTTP/1.1







